spring:
  config.name: ONLINE SHOPPING
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineshop
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show_sql: true
    database: postgresql
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
       enable_lazy_load_no_trans: true
       temp:
         use_jdbc_metadata_defaults: false
       jdbc:
         time_zone: UTC
         lob:
           non_contextual_creation: true
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    table: schema_version
    enabled: true
    group: true


#App Specific configuration
app:
  prod: false
  expiration-hours: 24
  jwt:
    header: Authorization
    secret: mySecret
    expiration: 604800
    route-authentication-path: /auth/login
    route-authentication-refresh: /auth/refresh
  pagination:
    default-page-num: 0
    default-elements-per-page: 20
  sorting:
    default-sort-type: desc
    default-sort-item: id

